### ISSUE TITLE
Unable to add more than one free upgrade

### ISSUE THREAD

**Issue by indyrcpilot** [grahamgilchrist/hotac-ship-builder#173]
The docs seem to indicate that more than one free upgrade can be added, but I'm not able to add more than one.

**Comment by grahamgilchrist** [comment]
Hi there.
I'm not sure exactly what you mean here. Can you give an example?

**Comment by indyrcpilot** [comment]
I think I was trying to add both integrated astro mech and guidance chips - both zero cost.

**Comment by grahamgilchrist** [comment]
HI. Integrated astromech is included by default in the xwing build as an automatic "free upgrade". Guidance chips requires use of a modification slot and can be equipped as a modification.

Here's a screenshot of this working:
![image](https://user-images.githubusercontent.com/632974/48634160-d5822600-e9bc-11e8-92db-e11595dc5db4.png)

**Comment by grahamgilchrist** [comment]
This all seems to be working as expected here. Unless there's more feedback, I'll close this issue?

**Comment by indyrcpilot** [comment]
Thanks for the clarification... per your other email, go ahead and close this issue.

 

Chuck
